//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narf.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Behaviour> Behaviours { get; set; }
        public virtual DbSet<BehaviourEvent> BehaviourEvents { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Pattern> Patterns { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Transition> Transitions { get; set; }
    }
}
