//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pattern
    {
        public long Id { get; set; }
        public long BehaviourId { get; set; }
        public long Hash { get; set; }
        public byte[] Raw { get; set; }
    
        public virtual Behaviour Behaviour { get; set; }
    }
}
