//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.BehaviourEvent = new HashSet<BehaviourEvent>();
            this.Position = new HashSet<Position>();
            this.Transition = new HashSet<Transition>();
        }
    
        public long Case_id { get; set; }
        public long Maze { get; set; }
        public long Date { get; set; }
        public Nullable<long> Dose { get; set; }
        public long Duration { get; set; }
        public string Notes { get; set; }
        public byte[] Preview { get; set; }
        public long Subjects { get; set; }
        public string Substance { get; set; }
        public long Videohash { get; set; }
        public long Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviourEvent> BehaviourEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transition> Transition { get; set; }
    }
}
