//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NarfDBEntities : DbContext
    {
        public NarfDBEntities()
            : base("name=NarfDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Behaviour> Behaviour { get; set; }
        public virtual DbSet<BehaviourEvent> BehaviourEvent { get; set; }
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<Pattern> Pattern { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Transition> Transition { get; set; }
    }
}
