//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pattern
    {
        public long Pattern_id { get; set; }
        public long Behaviour_id { get; set; }
        public byte[] Raw { get; set; }
        public long Hash { get; set; }
    
        public virtual Behaviour Behaviour { get; set; }
    }
}
