//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public long Position_id { get; set; }
        public long Case_id { get; set; }
        public long Time { get; set; }
        public long X { get; set; }
        public long Y { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
